export { getTenantResolver } from "./get-tenant.js";
export { getTenantsResolver } from "./get-tenants.js";
export { createTenantResolver } from "./create-tenant.js";
export { updateTenantResolver } from "./update-tenant.js";
export { deleteTenantResolver } from "./delete-tenant.js";
export { getTenantPropertyResolver } from "./get-tenant-property.js";
export { setTenantPropertyResolver } from "./set-tenant-property.js";
export { deleteTenantPropertyResolver } from "./delete-tenant-property.js";
export { tenantFieldResolvers } from "./tenant-field-resolvers.js";
